### ISSUE TITLE
SQLAlchemy version issue?

### ISSUE THREAD

**Issue by millerjohnp** [ludwigschmidt/basicdb#6]
It looks like `sqlalchemy` just updated their release to `1.4.0`. Using this version of `sqlachemy` raises an error in basicdb (see below), so pip installing basicdb currently fails. A fix would be simply requiring `sqlachemy<1.4.0`, but I want to make sure that's the best solution before updating the `pyproject.toml`.

```
~/research/pums/testbed/testbed/mldb.py in <module>
----> 1 import basicdb
      2 import os
      3 import pathlib
      4 
      5 from . import dataset

~/anaconda3/envs/pums/lib/python3.8/site-packages/basicdb/__init__.py in <module>
      1 __version__ = '0.0.12'
      2 
----> 3 from .basicdb import *
      4 from .entities import *
      5 from .exceptions import *

~/anaconda3/envs/pums/lib/python3.8/site-packages/basicdb/basicdb.py in <module>
      9 from .entities import *
     10 from .exceptions import *
---> 11 from .sql_adapter import SQLAdapter
     12 from . import utils
     13 

~/anaconda3/envs/pums/lib/python3.8/site-packages/basicdb/sql_adapter.py in <module>
      4 
      5 import sqlalchemy as sqla
----> 6 import sqlalchemy_utils
      7 
      8 from . import basicdb

~/anaconda3/envs/pums/lib/python3.8/site-packages/sqlalchemy_utils/__init__.py in <module>
----> 1 from .aggregates import aggregated  # noqa
      2 from .asserts import (  # noqa
      3     assert_max_length,
      4     assert_max_value,
      5     assert_min_value,

~/anaconda3/envs/pums/lib/python3.8/site-packages/sqlalchemy_utils/aggregates.py in <module>
    370 from sqlalchemy.sql.functions import _FunctionGenerator
    371 
--> 372 from .functions.orm import get_column_key
    373 from .relationships import (
    374     chained_join,

~/anaconda3/envs/pums/lib/python3.8/site-packages/sqlalchemy_utils/functions/__init__.py in <module>
----> 1 from .database import (  # noqa
      2     create_database,
      3     database_exists,
      4     drop_database,
      5     escape_like,

~/anaconda3/envs/pums/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py in <module>
      9 
     10 from ..utils import starts_with
---> 11 from .orm import quote
     12 
     13 

~/anaconda3/envs/pums/lib/python3.8/site-packages/sqlalchemy_utils/functions/orm.py in <module>
     12 from sqlalchemy.orm.exc import UnmappedInstanceError
     13 from sqlalchemy.orm.properties import ColumnProperty, RelationshipProperty
---> 14 from sqlalchemy.orm.query import _ColumnEntity
     15 from sqlalchemy.orm.session import object_session
     16 from sqlalchemy.orm.util import AliasedInsp

ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/Users/miller_john/anaconda3/envs/pums/lib/python3.8/site-packages/sqlalchemy/orm/query.py)

​
```

**Comment by ludwigschmidt** [comment]
Yes I think that's the best solution for now. The error actually comes from `sqlalchemy_utils`, which is a separate package that our requirements file has fixed to 0.36.7 because the latest 0.36.8 release had some problems. It looks like the `sqlalchemy_utils` developers are actively working on a fix: https://github.com/kvesteri/sqlalchemy-utils/pull/506

Until that is done, let's go with `sqlalchemy` 1.3.x.

**Comment by millerjohnp** [comment]
Looks like  kvesteri/sqlalchemy-utils#506 has been merged, which fixes this issue. Can we update `sqlalchemy_utils` to `0.37.0`? Or are there known problems with anything path  0.36.7?

**Comment by ludwigschmidt** [comment]
Yup that sounds good. Let me quickly test it locally. I was trying to upgrade the basicdb dependencies just now but this resulted in me having to install a Rust compiler on Mac for installing the latest version of a Python crypto library :-)  Will finish this tomorrow.

**Comment by ludwigschmidt** [comment]
Updated basicdb to 0.0.13 , which now works with SQLAlchemy 1.4 and sqlalchemy_utils 0.37 .
